### ISSUE TITLE
Support for Qt Creator 4.0.0>=beta1

### ISSUE THREAD

**Issue by ronjouch** [OneMoreGres/qtc-cppcheck#15]
Trying to use version 3.6.0 of the plugin with the newly released [Qt Creator 4.0.0beta1](https://blog.qt.io/blog/2016/03/23/qt-creator-4-0-beta-released/), it appears in an error state and the "Error Details" button of the "Installed Plugins" shows:

```
Could not resolve dependency 'Core(3.6.0)'
Could not resolve dependency 'ProjectExplorer(3.6.0)'
```

**Comment by OneMoreGres** [comment]
It shouldn't work :) I'll make 4.0.0 version near/after official Qt Creator's release.

**Comment by Spaghetti-Cat** [comment]
@OneMoreRes v4.0.0 was released yesterday :) I would love to see this plugin also work with v4. Thank you for this software

**Comment by Spaghetti-Cat** [comment]
@OneMoreRes v4.0.0 was released yesterday :) I would love to see this plugin also work with v4. Thank you for this software

**Comment by OneMoreGres** [comment]
Updated it.

**Comment by jibintao** [comment]
Hi Sir,  I installed Qt Creator 4.5.1 and qtc-cppcheck  4.3.0, but when I restart my Qt Creator, there is an error oucrred as:   ould not resolve dependency 'Core(4.4.0)'
Could not resolve dependency 'ProjectExplorer(4.3.0)',

I tried to compile your code, but there are many dependency file absence, could you give me some advices? thanks!  Michael, email: bintao.ji@qq.com

**Comment by OneMoreGres** [comment]
Hi, Michael!
Plugin's version must match Qt Creator's version (difference in last digit is acceptable). Version for qtc 4.5.1 is [here](https://github.com/OneMoreGres/qtc-cppcheck/releases/tag/4.5.0).
