### ISSUE TITLE
Ability to exclude files from check

### ISSUE THREAD

**Issue by Spaghetti-Cat** [OneMoreGres/qtc-cppcheck#17]
I can't figure out how to exclude files or directories from the check (I have some source files I must not change, but create many cppcheck warnings).

`cppcheck` has a switch `--config-exclude`, but if I add `--config-exclude=/absoulet/path/to/exclude_dir` to "custom parameters" in the Settings it doesn't have an effect: warnings from source files in `exclude_dir` still show in QtCreator.

PS: Big thanks for this plugin :) It allows me to catch problems early.

**Comment by OneMoreGres** [comment]
Hi. ` --suppress="*:<file_name_wildcard>"` should help.

As i understood from documentation, cppcheck doesn't count ifdefs found in `--config-exclude`, but checks files anyway.

**Comment by Spaghetti-Cat** [comment]
Fantastic! Thank you! I misread the manual. No more spam from auto-generated source files
