### ISSUE TITLE
Qt Creator 4.1.0 Support

### ISSUE THREAD

**Issue by elkvis** [OneMoreGres/qtc-cppcheck#18]
4.0 version does not work with Qt Creator 4.1.0.  Qt Creator reports that there were errors, and the plugin will be disabled.

**Comment by OneMoreGres** [comment]
It happens every major/minor update. I'll rebuild plugin soon.

**Comment by OneMoreGres** [comment]
Uploaded.

**Comment by elkvis** [comment]
Many thanks!
