### ISSUE TITLE
"Check current project" doesn't work in QtCreator 4.1.0 for Linux (x64)

### ISSUE THREAD

**Issue by evertondornelas** [OneMoreGres/qtc-cppcheck#19]
Using QtCreator 4.10 in Linux (_Ubuntu Gnome 16.04.1_ and _Ubuntu 16.04.1_), the option `Tools -> CppCheck -> Check current project` doesn't work.

No action appears to be taken when the option is selected (or when the shortcut `[Alt+C, Ctrl+A]` is used).

> I tested Windows version and it works fine.

**Comment by OneMoreGres** [comment]
Hi.
Tested on several systems including 16.04.1 - works for me.
You can enable `show binary's output` option to see some details about cppcheck invocation.

**Comment by evertondornelas** [comment]
Do a test with `Autotools` project.

You need to enable `AutotoolsProjectManager` in `Help -> About Plugins -> Build Systems`.

When I did a test with Qmake project, worked without problems. But the same didn't occurs with an Autotools project.

**Comment by OneMoreGres** [comment]
Looks like it doesn't work only when you open project for the first time. Possible qtc can't provide project's files list when plugin requests it. It starts working when you change active project.
However, now plugin reparses project if it looked empty before.

[QtcCppcheck-4.1.0-linux-x64.tar.gz](https://github.com/OneMoreGres/qtc-cppcheck/files/559940/QtcCppcheck-4.1.0-linux-x64.tar.gz)
