### ISSUE TITLE
Document how to use plugin

### ISSUE THREAD

**Issue by kubark42** [OneMoreGres/qtc-cppcheck#35]
This plugin looks great. However, when adding it to the appropriate path on Qt Creator, it seems to load properly (I see it in the list of available plugins) but I'm unsure what to do next. Could the readme be updated to indicate what next steps are?

**Comment by OneMoreGres** [comment]
There is a link with more detailed description at the end of readme. Is it enough?
[One of those description pages](https://translate.google.com/translate?hl=&sl=ru&tl=en&u=https%3A%2F%2Fgres.biz%2Fqtc-cppcheck-settings%2F)

**Comment by OneMoreGres** [comment]
Seems like it's enough :)
