### ISSUE TITLE
Cannot integrate qtc-cppcheck

### ISSUE THREAD

**Issue by hongsonitptit** [OneMoreGres/qtc-cppcheck#37]
I have downloaded qtc last version and copy binary to QtCreator as manual guide, but when I open QtCreator it was not show qtcCppcheck in Analyzer as image.
![untitled2](https://user-images.githubusercontent.com/5134089/32871676-0ff956f0-cab5-11e7-9d85-e24b62c8ebd6.png)
I am using Qt 5.4 and QtCreator 3.3.1
Please help me! Thanks

**Comment by OneMoreGres** [comment]
Looks like [plugin's version doesn't match Qt Creator's version](https://github.com/OneMoreGres/qtc-cppcheck#installation).
Try download 3.3.1 version of plugin (or upgrade qt creator to latest version).

**Comment by OneMoreGres** [comment]
Assume i was right.
