### ISSUE TITLE
Analysis of project with v4.5.0 (Windows) is significantly slower than CppCheck GUI

### ISSUE THREAD

**Issue by cchambers1982** [OneMoreGres/qtc-cppcheck#38]
I took the 4.5.0 release for Windows and integrated it with Qt Creator 4.5.0 (x86) and CppCheck v1.81 on Windows 10 (x64). The analysis is notably slower than with 4.3.0 and the same version of CppCheck, and with the CppCheck GUI. Both of those take around 10 minutes with my solution, but with v4.5.0 I gave up after 20 minutes at 10% done.

**Comment by OneMoreGres** [comment]
Can't inspect precisely right now (away), but there are some questions:

* does all plugin's runs happen with same command line arguments? Enable 'show application output' in settings to see.
* input files has likely been passed to cppcheck via files. Does that files' content differ a lot between different plugin's versions? There was a related fix.
* does plugins and 'gui' perform threaded checks ("-j<number>" argument)? Some options disable threading.

Also note that plugin analyzes header files explicitly, while cppcheck-gui only processes them if they are included in some checked source (if i remember right). So plugin should always work slower then cppcheck-gui.

I'll be able to check it by myself only some days later.

**Comment by cchambers1982** [comment]
Hey Sergey,

Thanks for your response. To answer your questions:

- Yes, both the 4.3.0 and 4.5.0 plugins have exactly the same command line arguments:

4.3.0: Starting CppChecker with:C:/Program Files (x86)/Cppcheck/cppcheck.exe, --enable=warning,style,performance,portability,information,missingInclude,unusedFunction --template={file},{line},{severity},{id},{message} --file-list=C:/Users/cchambers/AppData/Local/Temp/qtcreator.H17816 --includes-file=C:/Users/cchambers/AppData/Local/Temp/qtcreator.I17816

4.5.0: Starting CppChecker with:C:/Program Files (x86)/Cppcheck/cppcheck.exe, --enable=warning,style,performance,portability,information,missingInclude,unusedFunction --template={file},{line},{severity},{id},{message} --file-list=C:/Users/cchambers/AppData/Local/Temp/qtcreator.B16232 --includes-file=C:/Users/cchambers/AppData/Local/Temp/qtcreator.H16232

- By input files, I assume you mean the temp files on the command line. I checked both and they are identical between 4.3.0 and 4.5.0. Both file list contains around 1600 files and the include file list is empty in both cases.

- I don't believe the plugin is utilising multiple threads in either version, as I don't see a -j command line argument. The GUI is using one thread:

![image](https://user-images.githubusercontent.com/35062760/34532060-a143adf0-f0ac-11e7-8938-a912f0c94e79.png)

...so I would have thought they'd be comparable. 

I also take your point about the plugin being slower than the GUI, however, considering the plugin at 4.3.0 and the GUI operate at roughly the same speed but 4.5.0 is much, much slower than both I'd say it's more likely there's an issue with the 4.5.0 plugin.

Thank you again for your input.

**Comment by OneMoreGres** [comment]
Just checked it. 4.3.0 and 4.5.0 works same for me. Unfortunately both are slow on large codebase (qt-creator) :(

But there are some nuances:

* As i said before, plugin explicitly checks header files, so it doubled checked files count in my case. This can be "fixed" by adding `*.h` or similar filter to plugin's ignored files setting. After i've done this, files list became almost the same as in cppcheck-gui.
* Anyway, cppcheck, manually invoked with same arguments, works as bad as launched by plugin. So trouble is in input files contents. I cleared includes file (`--includes-file=...`) and check speed became comparable with cppcheck-gui. But without specifying those include paths, cppcheck can ignore some errors.

So, back to your situation. Was includes file really empty in both cases (4.3.0/4.5.0)? It should be filled with directories, containing checked files.
If it was empty - i don't know how to reproduse your issue.
If not - it explains long file processing (cppcheck have to check a lot of paths to find (or not) includes). But doesn't lead to *proper* sollution, since that file is here for a reason :)

**Comment by cchambers1982** [comment]
Hi Sergey. So sorry for the delay in responding to you. 

Thank you for the hints. I added the exclusion for header files but it didn't appear to exclude them during the check, and indeed was still very slow to process. 

![image](https://user-images.githubusercontent.com/35062760/35113259-b754e83e-fc78-11e7-9367-04fbee3adfcd.png)

I was sure that includes-files was empty last time, but I just re-checked and this time it's not so perhaps I made a mistake somewhere along the line. There are some 70 lines of directory paths in there now, all part of my solution.

**Comment by OneMoreGres** [comment]
Hello again.

I'll dig into cppcheck's sources later. Maybe then i'll find the way to handle such situations properly.

`Ignore patterns` means that matched files will not be **passed** to cppcheck cli. But if one of passed files uses (includes) some of them, cppcheck will check it anyway.

Btw `check for unused functions` disables threading.

**Comment by OneMoreGres** [comment]
Try this version. Changes:

* pass to cppcheck part of project's INCLUDEPATH instead of paths of all checked files; 
* added option to completely disable include paths passing.

[QtcCppcheck-4.5.0-win1.zip](https://github.com/OneMoreGres/qtc-cppcheck/files/1649910/QtcCppcheck-4.5.0-win1.zip)

**Comment by cchambers1982** [comment]
Hi Sergey, this version is much, much faster! Thank you.

**Comment by prepas** [comment]
I have error:
C:\Qt\Qt5.7.0\Tools\QtCreator-4.5.0\lib\qtcreator\plugins\QtcCppcheck4.dll: Cannot load library C:\Qt\Qt5.7.0\Tools\QtCreator-4.5.0\lib\qtcreator\plugins\QtcCppcheck4.dll: Unknown error 0x000000c1.

What is wrong? I use Qt Creator 4.5.0 and I've downloaded QtcCppcheck-4.5.0-win1.zip.

**Comment by OneMoreGres** [comment]
@prepas Hi. Looks like there is something wrong with your Qt version. Qt Creator 4.5.0 is build with Qt 5.10, but it tries to load 5.7 version. Have you installed it via qt online installer? I test plugins only for that version.

**Comment by prepas** [comment]
No, I use Qt Creator 4.5.0 & Qt 5.7.0

**Comment by OneMoreGres** [comment]
If you use qt creator different to one from qt online installer, then you likely should rebuild plugin by yourself.
