### ISSUE TITLE
Qtcreator-4.5.0 failing to load QtcCppcheck4.dll

### ISSUE THREAD

**Issue by RMutharaju** [OneMoreGres/qtc-cppcheck#39]
Hi,

I have downloaded QtcCppcheck-4.5.0-win and unzipped the contents as instructed.
[from https://github.com/OneMoreGres/qtc-cppcheck/files/1649910/QtcCppcheck-4.5.0-win1.zip ]

Now, everytime I start Qtcreator-4.5.0  I get a pop-up from Plugin Loader Messages:
"The following plugins have errors and cannot be loaded:
QtcCppcheck

Details:
C:\Qt\qtcreator-4.5.0\lib\qtcreator\plugins\QtcCppcheck4.dll: Cannot load library
C:\Qt\qtcreator-4.5.0\lib\qtcreator\plugins\QtcCppcheck4.dll: Unknown error 0x000000c1."

About Qt creator..
Qt Creator 4.5.0
Based on Qt 5.10.0 (MSVC 2015, 64 bit)

Built on Dec 4 2017 04:12:33

Please let me know on how to fix this?

Thanks
Rakesh

**Comment by RMutharaju** [comment]
Seems like the .dll is not supported for QtCreator 4.5.0 64 bit version. Do you have 64 bit version as well?

**Comment by OneMoreGres** [comment]
Hi. No, there is no prebuilt x64 version of the plugin (since qt online installer offers only x86 Qt Creator). So i recommend you to reinstall QTC with that installer.
