### ISSUE TITLE
Decide how to continue with with Qt Creator >= 4.8

### ISSUE THREAD

**Issue by michaelweghorn** [OneMoreGres/qtc-cppcheck#44]
Qt Creator change https://codereview.qt-project.org/#/c/235703/ recently merged upstream adds cppcheck functionality to upstream Qt Creator via a new (experimental) cppcheck plugin. It might make sense to investigate this further and decide how to continue, e.g. either

* continue with qtc-cppcheck as an alternative
* try to get all relevant functionality implemented upstream and drop qtc-cppcheck

(I haven't had a closer look at the new upstream plugin yet, just tested quickly and it seems to basically work, but I feel unable to tell how it compares to qtc-cppcheck.)

**Comment by OneMoreGres** [comment]
I'm aware of this change (I'm the author). It checks currently opened documents from active project and shows issues via text marks (which is different but pretty close to QtcCppcheck's approach). 
QtcCppcheck will be marked as deprecated after 4.8 (maybe I'll build it for couple more versions).
