### ISSUE TITLE
Cannot install to QT 4.5.2..

### ISSUE THREAD

**Issue by GinaVulpes** [OneMoreGres/qtc-cppcheck#45]
I have Qtcreator 4.5.2.
I have copied the .so file in: /usr/lib/x86_64-linux-gnu/qtcreator/plugins

But when I launch the Qtcreator I get this error:

![Screenshot from 2019-03-25 10-58-22](https://user-images.githubusercontent.com/10170044/54910610-f61f3700-4eec-11e9-8508-791162fd3cdf.png)

Could you please help me to fix this?

**Comment by OneMoreGres** [comment]
Prebuilt versions are compatible with Qt Creator from http://download.qt.io.
It looks like you're using Qt Creator installed from a native package manager. So you should build the plugin from source or use Qt Creator from http://download.qt.io.
Similar to #22
